name: gradle jar
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - env:
          JAVA_OPTS: -Xmx10g -Xms4g
          GRADLE_OPTS: -Xmx10g -Xms4g
        run: |
          echo "org.gradle.jvmargs=-Xmx10g -Xms4g" > gradle.properties
          gradle jar --no-daemon
